### ISSUE TITLE
css-mediaquery does not work with comments in media queries and with Opera's device pixel ratio

### ISSUE THREAD

**Issue by rvock** [ericf/css-mediaquery#7]
Two samples which fail to parse:

``` css
@media (-o-min-device-pixel-ratio: 3 / 2) {
    body { background: url('hd-background.png'); }
}
```

``` css
@media (-webkit-min-device-pixel-ratio: 1.5),
    (min--moz-device-pixel-ratio: 1.5),
    /* Opera Device Pixel ratio not supported by css-mediaquery 0.1.2 */
    /* (-o-min-device-pixel-ratio: 3 / 2), */
    (min-device-pixel-ratio: 1.5) {
    body { background: url('hd-background.png'); }
}
```

This works:

``` css
@media (min-device-pixel-ratio: 1.5) {
    body { background: url('hd-background.png'); }
}
```
